ENCODER_ENABLE = yes
MOUSEKEY_ENABLE = yes
AUDIO_ENABLE = yes
TAP_DANCE_ENABLE = yes
SRC += muse.c


BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
STENO_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = yes
NKRO_ENABLE = yes
AUDIO_ENABLE = yes
RGBLIGHT_ENABLE = yes
UNICODE_ENABLE = yes

# from default
SRC += muse.c